-- Migration 005: seed wsws.venues (ski resorts)
-- Generated by scripts/generate_wsws_seed.py -- re-runnable (ON CONFLICT DO NOTHING)

INSERT INTO wsws.venues (id, slug, name, city, state, lat, lng)
VALUES
    ('756bcfc4-6363-4f71-91d2-747a85f88b4a', 'alpine-valley-resort', 'Alpine Valley Resort', 'East Troy', 'WI', 42.7381877, -88.429212),
    ('457122fd-ea0c-4b5e-afe0-09b5bc6e1ca5', 'camp-10-ski-area', 'Camp 10 Ski Area', 'Langlade County', 'WI', 45.3418, -89.1693),
    ('8ef076cd-1859-4351-a331-b8c388c7ced1', 'cascade-mountain', 'Cascade Mountain', 'Portage', 'WI', 43.4999066, -89.5147391),
    ('799f0dca-a049-4096-94ae-736ecceaa5ea', 'granite-peak', 'Granite Peak', 'Wausau', 'WI', 44.9292979, -89.6831699),
    ('94c39bc1-8474-4f35-8603-7923ee8068ea', 'kettlebowl-ski-hill', 'Kettlebowl Ski Hill', 'Antigo', 'WI', 45.2712, -88.9019),
    ('b8575a07-0eb3-48c2-9d99-de31451196cf', 'nordic-mountain', 'Nordic Mountain', 'Wild Rose', 'WI', 44.18, -89.2475),
    ('0841fa24-6f6a-45be-a300-fb9df308b93b', 'paul-bunyan-ski-hill', 'Paul Bunyan Ski Hill', 'Lakewood', 'WI', 45.3261, -88.5246),
    ('36b232b2-61bb-4e76-80a8-875af531377e', 'wilmot-mountain', 'Wilmot Mountain', 'Wilmot', 'WI', 42.5132, -88.1819),
    ('bad67816-5cdd-4068-a1a2-a8f06f27c793', 'blackjack-ski-resort', 'Blackjack Ski Resort', 'Bessemer', 'MI', 46.4667, -90.0455),
    ('76a7f5cc-0811-4d3b-9c53-9bc97f6f3c64', 'mount-bohemia', 'Mount Bohemia', 'Mohawk', 'MI', 47.3911, -88.0097),
    ('591aa2db-907a-4010-94c5-c3f6350f381b', 'mont-ripley', 'Mont Ripley', 'Hancock', 'MI', 47.126714, -88.5608029),
    ('7e16baa9-c973-4d93-b564-b5585707d3f8', 'porcupine-mountains', 'Porcupine Mountains', 'Ontonagon', 'MI', 46.7417805, -89.8018301),
    ('3893999d-460b-4027-9507-ab08b06687f8', 'ski-brule', 'Ski Brule', 'Iron River', 'MI', 46.0284509, -88.7055528),
    ('6aea4d4c-add0-4157-85e9-412e0cd46c9a', 'paoli-peaks', 'Paoli Peaks', 'Paoli', 'IN', 38.548, -86.4738),
    ('6af373a8-330f-48b3-bff6-2b0596ccec5e', 'perfect-north-slopes', 'Perfect North Slopes', 'Lawrenceburg', 'IN', 39.1471655, -84.8872606),
    ('49abd6d7-f7a4-4f05-9068-7cd3c895ba7a', 'terry-peak-ski-area', 'Terry Peak Ski Area', 'Lead', 'SD', 44.3522, -103.7652),
    ('18cc17be-f143-4b38-a9bd-cdd94c0edaf1', 'ober-gatlinburg', 'Ober Gatlinburg', 'Gatlinburg', 'TN', 35.7031855, -83.5587502)
ON CONFLICT (slug) DO NOTHING;
