#!/usr/bin/env python3
"""Generate migrations/004_seed_wswd.sql from /tmp/wswd_geodir_to_wc.csv.

Re-runnable. Reads CSV as UTF-8 (file is UTF-8 but contains cp1252 mojibake strings).
Fixes mojibake by re-encoding as cp1252 then decoding as utf-8.
"""
import csv
import re
import sys
import uuid
from pathlib import Path

CSV_PATH = Path("/tmp/wswd_geodir_to_wc.csv")
OUT_PATH = Path(__file__).resolve().parent.parent / "migrations" / "004_seed_wswd.sql"


def fix_mojibake(s: str) -> str:
    """Fix cp1252 mojibake: re-encode as cp1252 then decode as utf-8."""
    if not s or not any(ord(c) > 127 for c in s):
        return s.strip() if s else s
    try:
        return s.encode("cp1252").decode("utf-8").strip()
    except (UnicodeEncodeError, UnicodeDecodeError):
        return s.strip()


def slugify(s: str) -> str:
    s = s.lower().strip()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"[\s_]+", "-", s)
    s = re.sub(r"-+", "-", s)
    return s.strip("-")


def category_slug(raw: str) -> list:
    if not raw:
        return []
    parts = [p.strip() for p in raw.split(",") if p.strip()]
    return [slugify(p) for p in parts]


def escape_sql_string(s) -> str:
    if s is None:
        return "NULL"
    if not isinstance(s, str):
        s = str(s)
    return "'" + s.replace("'", "''") + "'"


def pg_array(items: list) -> str:
    if not items:
        return "ARRAY[]::TEXT[]"
    escaped = [escape_sql_string(i) for i in items]
    return "ARRAY[" + ", ".join(escaped) + "]"


def main():
    if not CSV_PATH.exists():
        print(f"CSV not found: {CSV_PATH}", file=sys.stderr)
        sys.exit(1)

    rows = []
    seen_slugs: set = set()
    skipped = 0

    with open(CSV_PATH, encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row.get("post_status", "").strip() != "publish":
                skipped += 1
                continue

            name = fix_mojibake(row.get("post_title", ""))
            slug_base = slugify(name)
            slug = slug_base
            counter = 1
            while slug in seen_slugs:
                slug = f"{slug_base}-{counter}"
                counter += 1
            seen_slugs.add(slug)

            address = fix_mojibake(row.get("post_address", "") or "")
            city = fix_mojibake(row.get("post_city", "") or "")
            state = fix_mojibake(row.get("post_region", "") or "")
            zip_code = (row.get("post_zip", "") or "").strip()
            lat_raw = (row.get("post_latitude", "") or "").strip()
            lng_raw = (row.get("post_longitude", "") or "").strip()
            website = fix_mojibake(row.get("geodir_website", "") or "")
            phone = fix_mojibake(row.get("geodir_contact", "") or "")
            email = fix_mojibake(row.get("geodir_email", "") or "")
            facebook = fix_mojibake(row.get("geodir_facebook", "") or "")
            twitter = fix_mojibake(row.get("geodir_twitterusername", "") or "")
            property_type = row.get("geodir_property_type", "") or ""
            featured_image = (row.get("featured_image", "") or "").strip()
            overall_rating = (row.get("overall_rating", "0") or "0").strip()
            rating_count_raw = (row.get("rating_count", "0") or "0").strip()
            is_featured_raw = (row.get("is_featured", "0") or "0").strip()

            categories = category_slug(property_type)

            try:
                avg_rating_val = float(overall_rating)
                avg_rating_sql = "NULL" if avg_rating_val == 0 else str(round(avg_rating_val, 2))
            except ValueError:
                avg_rating_sql = "NULL"

            try:
                rating_count = int(rating_count_raw)
            except ValueError:
                rating_count = 0

            is_featured = is_featured_raw in ("1", "true", "True")

            try:
                lat = float(lat_raw) if lat_raw else None
                lng = float(lng_raw) if lng_raw else None
            except ValueError:
                lat = lng = None

            row_id = str(uuid.uuid4())
            rows.append((
                row_id, slug, name, address or None, city or None, state or None,
                zip_code or None, lat, lng, website or None, phone or None,
                email or None, facebook or None, twitter or None,
                categories, is_featured, featured_image or None,
                avg_rating_sql, rating_count,
            ))

    print(f"Loaded {len(rows)} publish rows, skipped {skipped}")

    # Preview a few to check mojibake fix
    for r in rows[:5]:
        print(f"  {r[2]!r}")

    lines = [
        "-- Migration 004: seed wswd.venues (81 dance venues from whereshallwedance.com)",
        "-- Generated by scripts/generate_wswd_seed.py -- re-runnable (ON CONFLICT DO NOTHING)",
        "",
        "INSERT INTO wswd.venues (",
        "    id, slug, name, address, city, state, zip, lat, lng,",
        "    website, phone, email, facebook_url, twitter_handle,",
        "    categories, is_featured, primary_photo, avg_rating, rating_count",
        ") VALUES",
    ]

    value_rows = []
    for r in rows:
        (row_id, slug, name, address, city, state, zip_code,
         lat, lng, website, phone, email, facebook, twitter,
         categories, is_featured, featured_image,
         avg_rating_sql, rating_count) = r

        lat_sql = str(lat) if lat is not None else "NULL"
        lng_sql = str(lng) if lng is not None else "NULL"

        value_rows.append(
            f"    ({escape_sql_string(row_id)}, {escape_sql_string(slug)}, {escape_sql_string(name)}, "
            f"{escape_sql_string(address)}, {escape_sql_string(city)}, "
            f"{escape_sql_string(state)}, {escape_sql_string(zip_code)}, "
            f"{lat_sql}, {lng_sql}, "
            f"{escape_sql_string(website)}, {escape_sql_string(phone)}, "
            f"{escape_sql_string(email)}, {escape_sql_string(facebook)}, "
            f"{escape_sql_string(twitter)}, "
            f"{pg_array(categories)}, "
            f"{'true' if is_featured else 'false'}, "
            f"{escape_sql_string(featured_image)}, "
            f"{avg_rating_sql}, {rating_count})"
        )

    lines.append(",\n".join(value_rows))
    lines.append("ON CONFLICT (slug) DO NOTHING;")

    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
