#!/usr/bin/env python3
"""Generate migrations/005_seed_wsws.sql by geocoding 17 ski resorts via Nominatim.

Re-runnable. Cached geocode results are stored in scripts/wsws_geocode_cache.json.
Any resort that returns no result or implausible CONUS coords is skipped and logged.
CONUS bounding box: lat 24-49, lng -125 to -66.
"""
import json
import sys
import time
import uuid
from pathlib import Path
import urllib.request
import urllib.parse
import urllib.error

CACHE_PATH = Path(__file__).resolve().parent / "wsws_geocode_cache.json"
OUT_PATH = Path(__file__).resolve().parent.parent / "migrations" / "005_seed_wsws.sql"

RESORTS = [
    {"name": "Alpine Valley Resort", "city": "East Troy", "state": "WI"},
    {"name": "Camp 10 Ski Area", "city": "Langlade County", "state": "WI"},
    {"name": "Cascade Mountain", "city": "Portage", "state": "WI"},
    {"name": "Granite Peak", "city": "Wausau", "state": "WI"},
    {"name": "Kettlebowl Ski Hill", "city": "Antigo", "state": "WI"},
    {"name": "Nordic Mountain", "city": "Wild Rose", "state": "WI"},
    {"name": "Paul Bunyan Ski Hill", "city": "Lakewood", "state": "WI"},
    {"name": "Wilmot Mountain", "city": "Wilmot", "state": "WI"},
    {"name": "Blackjack Ski Resort", "city": "Bessemer", "state": "MI"},
    {"name": "Mount Bohemia", "city": "Mohawk", "state": "MI"},
    {"name": "Mont Ripley", "city": "Hancock", "state": "MI"},
    {"name": "Porcupine Mountains", "city": "Ontonagon", "state": "MI"},
    {"name": "Ski Brule", "city": "Iron River", "state": "MI"},
    {"name": "Paoli Peaks", "city": "Paoli", "state": "IN"},
    {"name": "Perfect North Slopes", "city": "Lawrenceburg", "state": "IN"},
    {"name": "Terry Peak Ski Area", "city": "Lead", "state": "SD"},
    {"name": "Ober Gatlinburg", "city": "Gatlinburg", "state": "TN"},
]

# CONUS bounding box
LAT_MIN, LAT_MAX = 24.0, 49.5
LNG_MIN, LNG_MAX = -125.0, -66.0


def geocode(name: str, city: str, state: str, cache: dict) -> tuple:
    key = f"{name}|{city}|{state}"
    if key in cache:
        return cache[key]["lat"], cache[key]["lng"]

    query = urllib.parse.urlencode({
        "q": f"{name}, {city}, {state}, USA",
        "format": "json",
        "limit": "1",
        "countrycodes": "us",
    })
    url = f"https://nominatim.openstreetmap.org/search?{query}"
    req = urllib.request.Request(url, headers={"User-Agent": "whereshallwe-seed/1.0"})

    time.sleep(1.1)
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode())
    except Exception as e:
        print(f"  ERROR geocoding {name}: {e}", file=sys.stderr)
        cache[key] = {"lat": None, "lng": None}
        return None, None

    if not data:
        print(f"  SKIP {name}: no geocode result", file=sys.stderr)
        cache[key] = {"lat": None, "lng": None}
        return None, None

    lat = float(data[0]["lat"])
    lng = float(data[0]["lon"])

    if not (LAT_MIN <= lat <= LAT_MAX and LNG_MIN <= lng <= LNG_MAX):
        print(f"  SKIP {name}: implausible coords {lat},{lng}", file=sys.stderr)
        cache[key] = {"lat": None, "lng": None}
        return None, None

    cache[key] = {"lat": lat, "lng": lng}
    return lat, lng


def slugify(s: str) -> str:
    import re
    s = s.lower().strip()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"[\s_]+", "-", s)
    s = re.sub(r"-+", "-", s)
    return s.strip("-")


def escape_sql_string(s) -> str:
    if s is None:
        return "NULL"
    if not isinstance(s, str):
        s = str(s)
    return "'" + s.replace("'", "''") + "'"


def main():
    cache: dict = {}
    if CACHE_PATH.exists():
        cache = json.loads(CACHE_PATH.read_text())
        print(f"Loaded {len(cache)} cached geocodes")

    rows = []
    for resort in RESORTS:
        name = resort["name"]
        city = resort["city"]
        state = resort["state"]
        lat, lng = geocode(name, city, state, cache)
        if lat is None or lng is None:
            print(f"  SKIPPED: {name}")
            continue
        print(f"  OK: {name} -> {lat:.4f},{lng:.4f}")
        rows.append({
            "id": str(uuid.uuid4()),
            "slug": slugify(name),
            "name": name,
            "city": city,
            "state": state,
            "lat": lat,
            "lng": lng,
        })

    CACHE_PATH.write_text(json.dumps(cache, indent=2))
    print(f"Saved cache to {CACHE_PATH}")

    print(f"\nGeocoded {len(rows)}/{len(RESORTS)} resorts")

    lines = [
        "-- Migration 005: seed wsws.venues (ski resorts)",
        "-- Generated by scripts/generate_wsws_seed.py -- re-runnable (ON CONFLICT DO NOTHING)",
        "",
        "INSERT INTO wsws.venues (id, slug, name, city, state, lat, lng)",
        "VALUES",
    ]

    value_rows = []
    for r in rows:
        value_rows.append(
            f"    ({escape_sql_string(r['id'])}, {escape_sql_string(r['slug'])}, "
            f"{escape_sql_string(r['name'])}, {escape_sql_string(r['city'])}, "
            f"{escape_sql_string(r['state'])}, {r['lat']}, {r['lng']})"
        )

    lines.append(",\n".join(value_rows))
    lines.append("ON CONFLICT (slug) DO NOTHING;")

    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
